/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crs_gui.views;

import crs_gui.models.Application;
import crs_gui.models.ApplicationStatusTableModel;
import crs_gui.models.CRS;
import crs_gui.models.User;
import crs_gui.models.Volunteer;
import crs_gui.models.Document;
import crs_gui.models.Document.DocumentType;
import crs_gui.models.VolunteerApplicationTableModel;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JSpinner;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author user
 */
public class VolunteerView extends javax.swing.JFrame {

    /**
     * Creates new form VolunteerView
     */
    private CRS crs;
    private User user;
    private VolunteerApplicationTableModel appModel;
    private ApplicationStatusTableModel appStatusModel;
    
    public VolunteerView(CRS crs, User user) {
        this.crs = crs;
        this.user = user;
        initComponents();
        appModel = new VolunteerApplicationTableModel(crs.getTrips());
        Volunteer volunteer = (Volunteer) user;
        appStatusModel = new ApplicationStatusTableModel(volunteer.getApplications());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgNewApplication = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtRemarks = new javax.swing.JTextField();
        btnApply = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        dlgViewStatus = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        btnClose = new javax.swing.JButton();
        dlgEditProfile = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        txtEditPassword = new javax.swing.JTextField();
        txtEditName = new javax.swing.JTextField();
        txtEditPhone = new javax.swing.JTextField();
        btnEditPassword = new javax.swing.JButton();
        btnEditName = new javax.swing.JButton();
        btnEditPhone = new javax.swing.JButton();
        btnUploadDoc = new javax.swing.JButton();
        txtFile = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        spnExpDay = new javax.swing.JSpinner();
        spnExpMonth = new javax.swing.JSpinner();
        spnExpYear = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbxDocType = new javax.swing.JComboBox<>();
        btnDoneEdit = new javax.swing.JButton();
        alert = new javax.swing.JDialog();
        alertText = new javax.swing.JLabel();
        btnOkay = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnNewApplication = new javax.swing.JButton();
        btnViewStatus = new javax.swing.JButton();
        btnEditProfile = new javax.swing.JButton();
        btnSignOut = new javax.swing.JButton();

        dlgNewApplication.setMaximumSize(new java.awt.Dimension(501, 362));
        dlgNewApplication.setMinimumSize(new java.awt.Dimension(501, 362));
        dlgNewApplication.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                dlgNewApplicationWindowActivated(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Remarks");

        btnApply.setText("Apply");
        btnApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRemarks, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnApply, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnApply)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRemarks, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dlgNewApplicationLayout = new javax.swing.GroupLayout(dlgNewApplication.getContentPane());
        dlgNewApplication.getContentPane().setLayout(dlgNewApplicationLayout);
        dlgNewApplicationLayout.setHorizontalGroup(
            dlgNewApplicationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgNewApplicationLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        dlgNewApplicationLayout.setVerticalGroup(
            dlgNewApplicationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgNewApplicationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dlgViewStatus.setMaximumSize(new java.awt.Dimension(438, 380));
        dlgViewStatus.setMinimumSize(new java.awt.Dimension(438, 380));
        dlgViewStatus.setPreferredSize(new java.awt.Dimension(438, 380));
        dlgViewStatus.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                dlgViewStatusWindowActivated(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(btnClose)
                .addContainerGap(175, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClose)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dlgViewStatusLayout = new javax.swing.GroupLayout(dlgViewStatus.getContentPane());
        dlgViewStatus.getContentPane().setLayout(dlgViewStatusLayout);
        dlgViewStatusLayout.setHorizontalGroup(
            dlgViewStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgViewStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dlgViewStatusLayout.setVerticalGroup(
            dlgViewStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgViewStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dlgEditProfile.setMaximumSize(new java.awt.Dimension(385, 325));
        dlgEditProfile.setMinimumSize(new java.awt.Dimension(385, 325));
        dlgEditProfile.setPreferredSize(new java.awt.Dimension(370, 325));
        dlgEditProfile.setSize(new java.awt.Dimension(385, 330));
        dlgEditProfile.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                dlgEditProfileWindowActivated(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnEditPassword.setText("Change");
        btnEditPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditPasswordActionPerformed(evt);
            }
        });

        btnEditName.setText("Change");
        btnEditName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditNameActionPerformed(evt);
            }
        });

        btnEditPhone.setText("Change");
        btnEditPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditPhoneActionPerformed(evt);
            }
        });

        btnUploadDoc.setText("Upload");
        btnUploadDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadDocActionPerformed(evt);
            }
        });

        jLabel7.setText("Password");

        jLabel2.setText("Name");

        jLabel3.setText("Phone");

        jLabel4.setText("Type");

        jLabel5.setText("Expiry");

        jLabel6.setText("File");

        cbxDocType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Visa Card", "Passport", "Certificate" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEditPassword)
                            .addComponent(txtEditName)
                            .addComponent(txtEditPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEditName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEditPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEditPhone)))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxDocType, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(spnExpDay, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(spnExpMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(spnExpYear, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFile, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUploadDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEditPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditPassword)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEditName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditName)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEditPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditPhone)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(cbxDocType, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(spnExpMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(spnExpYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(spnExpDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUploadDoc)
                .addContainerGap())
        );

        btnDoneEdit.setText("Done");
        btnDoneEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlgEditProfileLayout = new javax.swing.GroupLayout(dlgEditProfile.getContentPane());
        dlgEditProfile.getContentPane().setLayout(dlgEditProfileLayout);
        dlgEditProfileLayout.setHorizontalGroup(
            dlgEditProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgEditProfileLayout.createSequentialGroup()
                .addGroup(dlgEditProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgEditProfileLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dlgEditProfileLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(btnDoneEdit)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        dlgEditProfileLayout.setVerticalGroup(
            dlgEditProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgEditProfileLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDoneEdit)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        alert.setMaximumSize(new java.awt.Dimension(336, 130));
        alert.setMinimumSize(new java.awt.Dimension(336, 130));
        alert.setMixingCutoutShape(null);
        alert.setPreferredSize(new java.awt.Dimension(336, 130));

        alertText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        alertText.setText("You have to fill the textbox");

        btnOkay.setText("Okay");
        btnOkay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout alertLayout = new javax.swing.GroupLayout(alert.getContentPane());
        alert.getContentPane().setLayout(alertLayout);
        alertLayout.setHorizontalGroup(
            alertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alertLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alertText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(alertLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(btnOkay, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );
        alertLayout.setVerticalGroup(
            alertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alertLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(alertText, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOkay)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(240, 204));
        setMinimumSize(new java.awt.Dimension(240, 204));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Welcome back, Firuz");

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnNewApplication.setText("Apply for Trip");
        btnNewApplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewApplicationActionPerformed(evt);
            }
        });

        btnViewStatus.setText("Application Status");
        btnViewStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewStatusActionPerformed(evt);
            }
        });

        btnEditProfile.setText("Edit Profile");
        btnEditProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditProfileActionPerformed(evt);
            }
        });

        btnSignOut.setText("Sign Out");
        btnSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSignOut, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnNewApplication, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnViewStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                        .addComponent(btnEditProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnNewApplication)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditProfile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSignOut)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewApplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewApplicationActionPerformed
        dlgNewApplication.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnNewApplicationActionPerformed

    private void btnViewStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewStatusActionPerformed
        dlgViewStatus.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnViewStatusActionPerformed

    private void btnEditProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditProfileActionPerformed
        dlgEditProfile.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnEditProfileActionPerformed

    private void dlgNewApplicationWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dlgNewApplicationWindowActivated
        jTable1.setModel(appModel);
        jTable1.setAutoCreateRowSorter(true);// TODO add your handling code here:
    }//GEN-LAST:event_dlgNewApplicationWindowActivated

    private void btnApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyActionPerformed
        String id = jTable1.getModel().getValueAt(jTable1.getSelectedRow(),0).toString();
        Application app = new Application(LocalDate.now(),
                crs.findTrip(id), (Volunteer) user);
        app.setRemarks(txtRemarks.getText());
        crs.findTrip(id).addApplication(app);
        app.setTrip(crs.findTrip(id));
        showAlert("Success!", "You have successfully applied for trip!");
        System.out.println(crs.allApplications());// TODO add your handling code here:
    }//GEN-LAST:event_btnApplyActionPerformed

    private void dlgViewStatusWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dlgViewStatusWindowActivated
        jTable3.setModel(appStatusModel);
        jTable3.setAutoCreateRowSorter(true);// TODO add your handling code here:
    }//GEN-LAST:event_dlgViewStatusWindowActivated

    private void btnEditPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditPasswordActionPerformed
        if(txtEditPassword.getText().isBlank()) {
            showAlert("Empty field!", "Password cannot be blank! Please enter the password!");
        }
        else {
            user.setPassword(txtEditPassword.getText());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditPasswordActionPerformed

    private void btnEditNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditNameActionPerformed
        if(txtEditName.getText().isBlank()) {
            showAlert("Empty field!", "Name cannot be blank! Please enter the new name!");
        }
        else {
            user.setName(txtEditName.getText());
        }// TODO add your handling code here:
    }//GEN-LAST:event_btnEditNameActionPerformed

    private void btnEditPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditPhoneActionPerformed
        if(txtEditPhone.getText().isBlank()) {
            showAlert("Empty field!", "Phone cannot be blank! Please enter the phone number!");
        }
        else {
            user.setPhone(txtEditPhone.getText());
        }// TODO add your handling code here:
    }//GEN-LAST:event_btnEditPhoneActionPerformed

    private void btnUploadDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadDocActionPerformed
        DocumentType docType = DocumentType.VISA;
        if(cbxDocType.getSelectedIndex() == 0) {
            docType = DocumentType.VISA;
        }
        else if(cbxDocType.getSelectedIndex() == 1) {
            docType = DocumentType.PASSPORT;
        }
        else if(cbxDocType.getSelectedIndex() == 2) {
            docType = DocumentType.CERTIFICATE;
        }
        DateTimeFormatter dateFormat = DateTimeFormatter.ofPattern("d/M/yyyy");
        String dateStr = spnExpDay.getValue().toString() + '/' + spnExpMonth.getValue().toString() + '/' + spnExpYear.getValue().toString();
        LocalDate date = LocalDate.parse(dateStr, dateFormat);
        if(txtFile.getText().isBlank()) {
            showAlert("Empty field!", "File cannot be blank! Please enter the image file name.");
        }
        else {
            Document document = new Document(docType, date, txtFile.getText());
            Volunteer volunteer = (Volunteer) user;
            volunteer.add(document);
            System.out.println("Added!");
        }
    }//GEN-LAST:event_btnUploadDocActionPerformed

    private void dlgEditProfileWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dlgEditProfileWindowActivated
        LocalDate currentdate = LocalDate.now();
        int currentDay = currentdate.getDayOfMonth();
        JSpinner.NumberEditor editor = new JSpinner.NumberEditor(spnExpYear, "2021");
        spnExpYear.setEditor(editor);
        SpinnerModel day = new SpinnerNumberModel(currentdate.getDayOfMonth(), 1, 31, 1);
        SpinnerModel month = new SpinnerNumberModel(currentdate.getMonthValue(), 1, 12, 1);
        SpinnerModel year = new SpinnerNumberModel(currentdate.getYear(), 1, 10000, 1);
        spnExpDay.setModel(day);
        spnExpMonth.setModel(month);
        spnExpYear.setModel(year);// TODO add your handling code here:
    }//GEN-LAST:event_dlgEditProfileWindowActivated

    private void btnOkayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkayActionPerformed
        alert.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_btnOkayActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        dlgViewStatus.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignOutActionPerformed
        dispose();
        CRSView crs = new CRSView();
        crs.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnSignOutActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        jLabel6.setText("Welcome back, " + user.getName());// TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dlgNewApplication.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnDoneEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneEditActionPerformed
        dlgEditProfile.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_btnDoneEditActionPerformed
    
    public void showAlert(String title, String text) {
        alertText.setText(text);
        alert.setTitle(title);
        alert.setVisible(true);
    }
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog alert;
    private javax.swing.JLabel alertText;
    private javax.swing.JButton btnApply;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDoneEdit;
    private javax.swing.JButton btnEditName;
    private javax.swing.JButton btnEditPassword;
    private javax.swing.JButton btnEditPhone;
    private javax.swing.JButton btnEditProfile;
    private javax.swing.JButton btnNewApplication;
    private javax.swing.JButton btnOkay;
    private javax.swing.JButton btnSignOut;
    private javax.swing.JButton btnUploadDoc;
    private javax.swing.JButton btnViewStatus;
    private javax.swing.JComboBox<String> cbxDocType;
    private javax.swing.JDialog dlgEditProfile;
    private javax.swing.JDialog dlgNewApplication;
    private javax.swing.JDialog dlgViewStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JSpinner spnExpDay;
    private javax.swing.JSpinner spnExpMonth;
    private javax.swing.JSpinner spnExpYear;
    private javax.swing.JTextField txtEditName;
    private javax.swing.JTextField txtEditPassword;
    private javax.swing.JTextField txtEditPhone;
    private javax.swing.JTextField txtFile;
    private javax.swing.JTextField txtRemarks;
    // End of variables declaration//GEN-END:variables
}
